name: pipeline
run-name: ${{ github.actor }} is running CI/CD by Github Actions 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 🎯 Checkout repository
        uses: actions/checkout@v4

      - name: 🎯 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: 🎯 Install dependencies
        run: go get .

      - name: 🎯 Test with the Go CLI
        run: go test ./...

  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: 🎯 Checkout repository
        uses: actions/checkout@v4

      - name: 🎯 Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🎯 Get next version
        uses: MCKanpolat/auto-semver-action@v2
        id: versioning
        with:
          releaseType: patch 
          incrementPerCommit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🎯 Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            trungthinhbo/raz:latest
            trungthinhbo/raz:${{ steps.versioning.outputs.version }}
